### ISSUE TITLE
[Typo] Local reference to smithy crate in cargo.toml

### ISSUE THREAD

**Issue by cpoisson** [rbalicki2/rustactoe#1]
Nice job!

I followed your instructions build this project and noticed that the build was failing at:

```
error: failed to load source for a dependency on `smithy`

Caused by:
  Unable to update /home/charles/Workspace/wasm-playground/smithy/crates/smithy

Caused by:
  failed to read `/home/charles/Workspace/wasm-playground/smithy/crates/smithy/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I think there is maybe just a typo in your `cargo.toml` since b9548bd9

https://github.com/rbalicki2/rustactoe/blob/b9548bd957dcdfc1c7182891d05e46769b841d8a/Cargo.toml#L35

removing this path or cloning smithy at the correct location fix the issue.

**Comment by rbalicki2** [comment]
Ah, you're right! This local reference shouldn't be there any more. Thank you for finding this.
